DECLARE @c BIGINT = (SELECT COUNT(*) FROM STATION);

SELECT CAST(AVG(1.0 * LAT_N) AS DECIMAL(16, 4))
FROM (
    SELECT LAT_N FROM STATION
     ORDER BY LAT_N
     OFFSET (@c - 1) / 2 ROWS
     FETCH NEXT 1 + (1 - @c % 2) ROWS ONLY
) AS x;